services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - ../media/data/media:/data/media:ro
    restart: unless-stopped

volumes:
  jellyfin_config:
  jellyfin_cache: